services:
  app:
    image: todo_app
    container_name: todo_app_c
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    environment:
      APP_ENV: ${APP_ENV:-local}
      PORT: ${PORT:-8080}
