apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      first-deploy-app: log-output-app-1-3
  template:
    metadata:
      labels:
        first-deploy-app: log-output-app-1-3
    spec:
      containers:
        - name: log-output-ctr
          image: michaelangelovalente/log_output-app:ex1.03
