apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  labels:
    app: ping-pong
    version: "1.11"
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
      version: "1.11"
      component: backend
  template:
    metadata:
      labels:
        app: ping-pong
        version: "1.11"
        component: backend
    spec:
      volumes:
        - name: shared-logs-vol
          persistentVolumeClaim:
            claimName: ping-pong-claim

      containers:
        - name: log-writer-ctr
          image: michaelangelovalente/log_writer:ex1.11
          volumeMounts:
            - name: shared-logs-vol
              mountPath: /app/tmp/shared
          # ENV variables config
          env:
            # Application level env var (consumed by actual app)
            - name: WRITER_PORT
              value: "8091"
            - name: LOG_FILE_PATH
              value: "/app/tmp/shared/logs.txt"
          # Kubernetes level port declaration
          ports:
            - name: http-writer
              containerPort: 8091
              protocol: TCP

        - name: log-reader-ctr
          image: michaelangelovalente/log_reader:ex1.11
          volumeMounts:
            - name: shared-logs-vol
              mountPath: /app/tmp/shared
          # ENV variables config
          env:
            # Application level env var (consumed by actual app)
            - name: READER_PORT
              value: "8092"
            - name: LOG_FILE_PATH
              value: "/app/tmp/shared/logs.txt"
            - name: PING_PONG_FILE_PATH
              value: "/app/tmp/shared/pingpong.txt"
          ports:
            - name: http-reader
              containerPort: 8092
              protocol: TCP

        - name: ping-pong-ctr
          image: michaelangelovalente/ping_pong:ex1.11
          volumeMounts:
            - name: shared-logs-vol
              mountPath: /app/tmp/shared
          # ENV variables config
          env:
            # Application level env var (consumed by actual app)
            - name: PING_PONG_PORT
              value: "8093"
            - name: PING_PONG_FILE_PATH
              value: "/app/tmp/shared/pingpong.txt"
          # Kubernetes level port declaration
          ports:
            - name: http-pingpong
              containerPort: 8093
              protocol: TCP
