apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      first-deploy-app: todo-app-1-4
  template:
    metadata:
      labels:
        first-deploy-app: todo-app-1-4
    spec:
      containers:
        - name: todo-app-ctr
          image: michaelangelovalente/todo_app:ex1.04
