services:
  app:
    image: pingpong_img
    container_name: ping_pong_ctr
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
